src/components/Board.js
=> fix pull request urls

src/components/App.js
=> don't show 'release' stories

src/components/Board.js, src/components/Entry.js, src/components/SwimLane.js
=> show estimates

src/components/Board.js, src/components/Entry.js, src/components/SwimLane.js
=> align items to top

src/components/App.js, src/components/Board.js
=> get project name from API

src/.env.sample.js, src/components/App.js, src/index.js
Closes https://github.com/mojotech/pivotal-swimlanes/issues/5
=> Dynamically associate story owner id to project member

devServer.js, package.json, src/components/Setup.js, src/index.js
=> authenticate GitHub w/ OAuth

src/components/Settings.js, src/containers/ProjectContainer.js, src/containers/SettingsContainer.js
=> manage settings data in container

src/components/Settings.js, src/containers/SettingsContainer.js
>Fixes #55
>
>May want a more robust solution, but this allows quick searching and limiting by user, ie. mojotech/pivotal == q=pivotal+user:mojotech
https://github.com/mojotech/pivotal-swimlanes/pull/58
Thanks @markalfred.
(I resolved conflicts)
=> [markalfred] Add typeahead search for repos

src/components/Settings/Settings.js, src/index.js
=> use state parameter for apis to prevent csrf

src/components/Settings/Settings.js, src/containers/SettingsContainer.js
=> allow users to disconnect github/heroku accts

src/components/Settings/Settings.js, src/components/shared/Loading.js, src/containers/ProjectContainer.js, src/containers/SettingsContainer.js
=> Select from list of your pivotal projects

src/containers/ProjectContainer.js
=> don't show owner if not part of project anymore

src/containers/ProjectContainer.js
=> hide releases

src/components/Project/Board.js, src/components/Project/Project.js, src/containers/ProjectContainer.js
=> Render review column only if Github repo selected

src/components/Project/Entry.js, src/components/Project/SwimLane.js, src/containers/ProjectContainer.js
=> Handle multiple PRs that finish same Pivotal story

src/components/Project/HeaderBar.js, src/components/Settings/Settings.js
=> Fixes defined but never used errors, removed comment inside JSX code

src/components/Project/HeaderBar.js, src/components/Project/Project.js, src/components/Settings/Settings.js
=> Render HeaderBar in settings page

src/components/Settings/Settings.js
Set pivotal dropdown select value to the current project selected.
=> Fix pivotal dropdown

src/components/Settings/Settings.js, src/styles/form.scss
Removed inline styles from section heading, created class for section heading and added rules to the stylesheet. Also removed unused json style on settings page.
=> Minor style changes on setting page

src/components/Settings/Settings.js, src/containers/SettingsContainer.js
Added onBlur event to call fetchPivotalProjects.
Fixes #101
=> onblur-fetch-pivotal-projects

index.html, src/components/Project/Board.js, src/components/Project/HeaderBar.js, src/components/Project/SwimLane.js
=> Extend column separator heights to full height of body. Fixes #111

src/components/Settings/Settings.js
Adds button that allows user to remove current github repo
=> Adds remove repo button

src/components/shared/Loading.js
If there are no current stories, add a default message to check Pivotal after 5 seconds.
note:  branch based off master
=> Add a time out message

Procfile, config/prod.exs, phoenix_static_buildpack.config, web/channels/user_socket.ex
I followed this guide http://www.phoenixframework.org/docs/heroku
But I had to fork this buildpack since it used brunch by default https://github.com/djkirby/heroku-buildpack-phoenix-static
Deploys to https://pivotal-swimlanes.herokuapp.com
The initial setup of your settings isn't working yet though
=> setup for heroku
